# Exercise 1

* Use the dataset

```python
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
```
* Apply One-hot encoding to all variables
* Apply One-hot encoding to the first column and ordinal encoding to the second column following the rank Low, Medium, High

In [1]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [2]:
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]

In [3]:
encoder = ColumnTransformer([
    ('onehotencoder',OneHotEncoder(),[0,1])
])

encoder.fit_transform(X)

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.]])

In [7]:
encoder = ColumnTransformer([
    ('first_column', OneHotEncoder(), [0]),
    ('second_column', OrdinalEncoder(categories = [["Low","Medium","High"]]) ,[1])
])

encoder.fit_transform(X)

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 0.]])

# Exercise 2

* Use the dataset

```python
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
```
* Apply One-hot encoding to the first variable and ordinal encoding to the second variable. 
  * The first variable must be encoded considering this set of values: X, Y, Z, W. 
  * The second variable must be encoded considering this set of ranked values: Low, Medium, High, Very high
* Consider the dataset:
```python
Y = [["W","Very high"]]
```
* Transform this dataset according to the fitted encoder

In [8]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [9]:
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]

In [11]:
encoder = ColumnTransformer([
    ('first_column',OneHotEncoder(categories=[["X","Y","Z","W"]]), [0]),
    ('second_column', OrdinalEncoder(categories=[["Low","Medium","High","Very high"]]), [1])
])

encoder.fit_transform(X)

array([[1., 0., 0., 0., 2.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [14]:
Y = [["W","Very high"]]

In [15]:
encoder.transform(Y)

array([[0., 0., 0., 1., 3.]])