# Exercise

* Load **wine** dataset
* Apply standardization to the features
* Apply SMOTE to balance the target classes
* Invert standardization to go back to the original feature space

In [1]:
from sklearn.datasets import load_wine

from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import numpy as np

In [3]:
X, y = load_wine(return_X_y=True)

In [6]:
np.unique(y,return_counts=True)

(array([0, 1, 2]), array([59, 71, 48]))

In [7]:
scaler = StandardScaler()

In [8]:
X_scaled = scaler.fit_transform(X)

In [9]:
res = SMOTE(random_state = 0)

In [10]:
X_res, y_res = res.fit_resample(X_scaled, y)

In [11]:
X_res

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.06334972,  2.24313817,  0.39107263, ..., -1.73648411,
        -1.09841643, -0.30886394],
       [ 0.97276512,  0.54537381, -0.2036003 , ..., -1.20664012,
        -1.32359186, -0.47814445],
       [ 0.0508642 ,  1.83729472,  0.41481959, ..., -1.60395346,
        -1.19906182, -0.25914019]])

In [12]:
y_res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
np.unique(y_res,return_counts=True)

(array([0, 1, 2]), array([71, 71, 71]))

In [15]:
X_final = scaler.inverse_transform(X_res)