In [10]:
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PowerTransformer

In [9]:
X = [[1], [2],[np.nan],[3]]

In [11]:
cleaner = SimpleImputer()
power = PowerTransformer()

In [12]:
X_clean = SimpleImputer().fit_transform(X)

In [13]:
X_final = PowerTransformer().fit_transform(X_clean)

In [14]:
X_final

array([[-1.43683574],
       [ 0.02299616],
       [ 0.02299616],
       [ 1.39084342]])

# The pipeline object

In [18]:
from sklearn.pipeline import make_pipeline, Pipeline

In [16]:
pipeline = make_pipeline(SimpleImputer(), PowerTransformer())

In [17]:
pipeline.fit_transform(X)

array([[-1.43683574],
       [ 0.02299616],
       [ 0.02299616],
       [ 1.39084342]])

In [19]:
pipeline = Pipeline([
    ('cleaning', SimpleImputer()),
    ('power_transformer', PowerTransformer())
])

In [20]:
pipeline.fit_transform(X)

array([[-1.43683574],
       [ 0.02299616],
       [ 0.02299616],
       [ 1.39084342]])

In [21]:
pipeline.set_params(cleaning__strategy = 'median')

Pipeline(steps=[('cleaning', SimpleImputer(strategy='median')),
                ('power_transformer', PowerTransformer())])

In [22]:
pipeline.fit_transform(X)

array([[-1.43683574],
       [ 0.02299616],
       [ 0.02299616],
       [ 1.39084342]])